### ISSUE TITLE
doc: architecture link is broken in get-started.md

### ISSUE THREAD

**Issue by dotdc** [vdaas/vald#1618] opened 2022-04-12 12:47 UTC
### Describe the bug:

The architecture link is broken in `get-started.md`

### To Reproduce:

Go on https://vald.vdaas.org/docs/tutorial/get-started/ and click on the Architecture link.

### Expected behavior:

Should open : https://vald.vdaas.org/docs/overview/architecture 
Instead, the broken link points to : https://vald.vdaas.org/docs/docs/overview/architecture

### Environment:

- Go Version: 1.18
- Docker Version: 20.10.8
- Kubernetes Version: 1.22.0
- NGT Version: 1.14.3

**Comment by vankichi** [comment] 2022-04-13 04:04
Hi, @dotdc !
Thanks for the bug report and PR :)
The root cause will be resolved when your PR will be merged.

FYI:
We deploy Vald website from https://github.com/vdaas/web with syncing documents in this repository.
So, the website won't fix by only your PR. 
I'm going to fix website with correct link by https://github.com/vdaas/web/pull/103.

Thanks :)

**Closed** 2022-04-13 08:28 UTC
Labels: type/bug, team/core, priority/medium

**Comment by vankichi** [comment] 2022-04-13 09:04
@dotdc 
Thanks for contributing!
And welcome to Vald contributors :tada: 
Vald Website has been updated :arrow_right: https://vald.netlify.app/docs/tutorial/get-started/
